name: Telegram Reminder

on:
  schedule:
    - cron: '0 1 * * *'   # 08:00 WIB
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependency
        run: npm install node-fetch@2

      - name: Run reminder
        run: node send.js
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
