name: Reminder Bot

on:
  schedule:
    # Jadwal: Setiap jam 08:00 WIB (approx 01:00 UTC)
    - cron: '0 01 * * *' 
  # Opsional: Biarkan bisa dijalankan manual lewat tombol "Run workflow"
  workflow_dispatch:

jobs:
  send-reminder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        # Hanya perlu install axios (HTTP Client)
        run: npm install axios
        
      - name: Run Reminder Script
        env:
          BIN_ID: ${{ secrets.BIN_ID }}
          MASTER_KEY: ${{ secrets.MASTER_KEY }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: node send.js
